### ISSUE TITLE
No download asset available for target darwin-aarch64

### ISSUE THREAD

**Issue by kavsingh** [owenizedd/bum#14]
install.sh fails with a 404

it specifies a target for darwin arm64: https://github.com/owenizedd/bum/blob/main/install.sh#L14
but there is no asset for the target in the latest release: https://github.com/owenizedd/bum/releases/tag/v0.5.0

```zsh
curl --fail --location --progress-bar --output ~/.bum/bin/bum https://github.com/owenizedd/bum/releases/latest/download/bum-darwin-aarch64

curl: (22) The requested URL returned error: 404
```

**Comment by azulkipli** [comment]
is the error 
```
curl -fsSL https://github.com/owenizedd/bum/raw/main/install.sh | sh -
curl: (22) The requested URL returned error: 404
```
related to this issue?

**Comment by owenizedd** [comment]
If you're using darwin arm64 currently it's not supported, right now this project support mac intel, but I'll work to make it support more platforms when I have the time

**Comment by fourcolors** [comment]
Would love to see this work on arm as well.

**Comment by owenizedd** [comment]
We have updated bum to support more architecture feel free to try again now :)
