### ISSUE TITLE
Two manual steps I had to take with the latest release

### ISSUE THREAD

**Issue by robertherber** [owenizedd/bum#19]
Love seeing some action here! I just got the latest version running on my M1 Mac after doing the following manually:
- I most probably got the wrong version of the binary when running the install script, resulting in `zsh: exec format error: bum`. I fixed this by downloading the aarch64-apple-darwin binary manually.
- The install script didn't create the required `~/.bum/bun-versions` folder, so I created it manually.

**Comment by owenizedd** [comment]
I recognized there were some issues with install.sh I just pushed some changes do you mind to retry, does it still exist?

Because I got exactly same issue

**Comment by owenizedd** [comment]
ah, right I didn't see the bun-versions

**Comment by robertherber** [comment]
It seems to work now :) I guess this means #14 is also fixed now?

**Comment by robertherber** [comment]
And thanks for creating this utility - been missing something like this. Even though bun strives to be evergreen I think it's important to be able to be deterministic about versions - just as it's important to have a lock-file.. :)

**Comment by owenizedd** [comment]
Yes now the repo has action that generate for multi OS
